// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCW4xGjvhel1aou88hHoYQwqpCuUGLEzE',
    appId: '1:481785650994:web:2398346e4379c2b5d8c12b',
    messagingSenderId: '481785650994',
    projectId: 'lapor-book-e5fa6',
    authDomain: 'lapor-book-e5fa6.firebaseapp.com',
    storageBucket: 'lapor-book-e5fa6.appspot.com',
    measurementId: 'G-V81K330ZVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBb9FvheFX75DanFUMsPM3_lx49a57NoI',
    appId: '1:481785650994:android:8a87f772d7903ffcd8c12b',
    messagingSenderId: '481785650994',
    projectId: 'lapor-book-e5fa6',
    storageBucket: 'lapor-book-e5fa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UpQFgM4GbRwFRdSFMjpgKC1gupAHu34',
    appId: '1:481785650994:ios:bd55018587d36d5ed8c12b',
    messagingSenderId: '481785650994',
    projectId: 'lapor-book-e5fa6',
    storageBucket: 'lapor-book-e5fa6.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UpQFgM4GbRwFRdSFMjpgKC1gupAHu34',
    appId: '1:481785650994:ios:791059da2f757278d8c12b',
    messagingSenderId: '481785650994',
    projectId: 'lapor-book-e5fa6',
    storageBucket: 'lapor-book-e5fa6.appspot.com',
    iosBundleId: 'com.example.laporBook.RunnerTests',
  );
}
